### ISSUE TITLE
uncaught target signal 11

### ISSUE THREAD

**Issue by srikanth007m** [bromodachi/Cache_Simulator#1]
I've tried this cache simulator and not able to launch it. Getting SIGSEGV signal. Also it would be great if you can provide some example of how to launch the simulator. It helps novice users like me. 

///
uname({sys="Linux", node="1-linux", ...}) = 0
mmap(0x7fbe1bdad000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbe1bdad000
getcwd("/local/mnt2/workspace2/tools/Cache_Simulator/simulator", 4096) = 55
lstat("/local/mnt2/workspace2/tools/Cache_Simulator/simulator/cache-test", {st_mode=S_IFREG|0775, st_size=730570, ...}) = 0
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fbe1bcb6000
mmap(0x7fbe1bdae000, 135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fbe1bdae000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("trace.out", O_RDONLY)             = 3
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7fbe1bd03044} ---
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
getrlimit(RLIMIT_CORE, {rlim_cur=0, rlim_max=RLIM64_INFINITY}) = 0
getrlimit(RLIMIT_CORE, {rlim_cur=0, rlim_max=RLIM64_INFINITY}) = 0
setrlimit(RLIMIT_CORE, {rlim_cur=0, rlim_max=RLIM64_INFINITY}) = 0
futex(0x6254d960, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "qemu: uncaught target signal 11 "..., 67qemu: uncaught target signal 11 (Segmentation fault) - core dumped
) = 67
rt_sigaction(SIGSEGV, {SIG_DFL, ~[RTMIN RT_1], SA_RESTORER, 0x60124550}, NULL, 8) = 0
kill(9444, SIGSEGV)                     = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_USER, si_pid=9444, si_uid=204405} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
///

**Comment by bromodachi** [comment]
Hello! First off, thank you for visiting my git.

The code is fairly old now so I'm pretty sure there might be some bugs. Anyway, basically you need a trace file to run the program and if you type in "-h", it should tell you how to run the program. I uploaded the trace files in case you want to run it.

**Comment by srikanth007m** [comment]
Thank you for the prominent reply. It would be great if you can give me some example on how to launch this cache simulator with supported arguments. I've given a try and it is showing the same crash dump every time. Might be i am not familiar.

**Comment by bromodachi** [comment]
To run the program:
1. Run make
2. Here is an example to run the program 
"./cache-sim -l1size 16384 l1-assoc direct 512 fifo lstrace.txt"
Another:
"./cache-sim -l1size 16384 l1-assoc assoc 512 fifo lstrace.txt"
The result will print.

I realized I never checked if the user never runs the program with no args. The code is now 2 years old so sorry about that. Maybe I'll go back to this code and catch other bugs or maybe even improve it.

**Comment by srikanth007m** [comment]
I've given a try of the above said example with different tunables. But still it is returning "ERROR: <Please enter the correct argument>".

**Comment by bromodachi** [comment]
Could you provide a screen shot of how you are running it?

**Comment by srikanth007m** [comment]
This is what i am able to see from help.. 
-l1size <L1 size> -l1assoc <L1 assoc>
-l2size <L2 size> -l2assoc <L2 assoc>
-l3size <L3 size> -l3assoc <L3 assoc> <block size> <replace alg> <trace file>

I'm trying to launch the simulator like
cache-sim -l1size 1024 l1-assoc direct 256 fifo gccTraceFile.txt
ERROR: <Please enter the correct argument>

**Comment by bromodachi** [comment]
You should be running it like:
"./cache-sim -l1size 1024 -l1assoc direct 256 fifo gccTraceFile.txt"

Sorry if running the program wasn't clear enough.

**Comment by bromodachi** [comment]
To see the help menu as well:
"./cache-sim -h"

**Comment by srikanth007m** [comment]
Now it returns of something. Thanks.

**Comment by bromodachi** [comment]
No problem. Since it seems to be working, I'll close is now. 

Thank you again for visiting my github page.
